# Generated by Django 2.1.5 on 2019-03-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0012_auto_20190325_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegServant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('job', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profilepics/')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.BloodGrp')),
            ],
        ),
    ]
