# Generated by Django 2.1.5 on 2019-03-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regservant',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
