# Generated by Django 2.1.5 on 2019-03-26 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_regservant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='regservant',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 6, 47, 52, 640524, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regservant',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
