# Generated by Django 2.1.5 on 2019-04-01 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190327_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regservant',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
