# Generated by Django 2.1.5 on 2019-04-01 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20190401_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regservant',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
