# Generated by Django 2.1.5 on 2019-04-01 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20190401_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regservant',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
