# Generated by Django 2.1.5 on 2019-04-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_jobtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regservant',
            name='job',
        ),
    ]
