# Generated by Django 2.1.5 on 2019-04-04 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_remove_regservant_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='regservant',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.JobType'),
            preserve_default=False,
        ),
    ]
