# Generated by Django 2.1.5 on 2019-04-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_regservant_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='regservant',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
