# Generated by Django 2.1.5 on 2019-05-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_regservant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regservant',
            name='photo',
            field=models.ImageField(blank=True, default='profilepics/default.jpg', upload_to='profilepics/'),
        ),
    ]
