# Generated by Django 2.1.5 on 2019-05-11 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCtg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BloodGrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_grp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('job', models.CharField(blank=True, max_length=50)),
                ('house_name', models.CharField(blank=True, max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('photo', models.ImageField(blank=True, default='profilepics/default.jpg', upload_to='profilepics/')),
                ('blood_group', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='login.BloodGrp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
