# Generated by Django 2.1.5 on 2019-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190320_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/'),
        ),
    ]
