# Generated by Django 2.1.5 on 2019-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190320_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
