# Generated by Django 2.1.5 on 2019-03-20 17:49

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190320_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='house_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reguser',
            name='house_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reguser',
            name='job',
            field=models.CharField(blank=True, max_length=50),
        ),

        migrations.AlterField(
            model_name='reguser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager')], max_length=10),
        ),
    ]
