# Generated by Django 2.1.5 on 2019-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190320_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
