# Generated by Django 2.1.5 on 2019-03-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190320_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
