# Generated by Django 2.1.5 on 2019-03-22 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0008_reguser_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_grp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MemReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('job', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.BloodGrp')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='reguser',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='reguser',
            name='blood_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='login.BloodGrp'),
            preserve_default=False,
        ),
    ]
