# Generated by Django 2.1.5 on 2019-03-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_memreg_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memreg',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/profilepics/'),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/profilepics/'),
        ),
    ]
