# Generated by Django 2.1.5 on 2019-03-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190322_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memreg',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profilepics/'),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profilepics/'),
        ),
    ]
