# Generated by Django 2.1.5 on 2019-03-27 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0012_auto_20190325_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCtg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi')], max_length=50)),
                ('description', models.TextField()),
                ('book_file', models.FileField(upload_to='bookfiles/')),
                ('status', models.BooleanField(default=False)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.BookCtg')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
