# Generated by Django 2.1.5 on 2019-03-27 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0013_bookctg_bookdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookDetails',
            new_name='BookDetail',
        ),
    ]
