# Generated by Django 2.1.5 on 2019-03-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190327_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetail',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='bookdetail',
            name='username',
        ),
        migrations.RemoveField(
            model_name='memreg',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='memreg',
            name='username',
        ),
        migrations.DeleteModel(
            name='BookCtg',
        ),
        migrations.DeleteModel(
            name='BookDetail',
        ),
        migrations.DeleteModel(
            name='MemReg',
        ),
    ]
