# Generated by Django 2.1.5 on 2019-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_activityctg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
