# Generated by Django 2.1.5 on 2019-04-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20190404_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User')], max_length=10),
        ),
    ]
