# Generated by Django 2.1.5 on 2019-04-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20190404_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager')], max_length=10),
        ),
    ]
