# Generated by Django 2.1.5 on 2019-05-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_remove_reguser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='blood_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='login.BloodGrp'),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profilepics/'),
        ),
    ]
