# Generated by Django 2.1.5 on 2019-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20190506_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='photo',
            field=models.ImageField(blank=True, default='profilepics/default.jpg', upload_to='profilepics/'),
        ),
    ]
