# Generated by Django 2.1.5 on 2019-05-12 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campregistration',
            name='description',
        ),
        migrations.AddField(
            model_name='campregistration',
            name='payment',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campregistration',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campregistration',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
