# Generated by Django 2.1.5 on 2019-04-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcampregistration',
            name='status',
            field=models.CharField(default='Pending', max_length=25),
        ),
    ]
