# Generated by Django 2.1.5 on 2019-04-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_auto_20190412_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcampregistration',
            name='type',
        ),
    ]
