# Generated by Django 2.1.5 on 2019-04-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0003_remove_medcampregistration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcampregistration',
            name='doc_contact',
        ),
        migrations.RemoveField(
            model_name='medcampregistration',
            name='doc_name',
        ),
    ]
