# Generated by Django 2.1.5 on 2019-04-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0004_auto_20190423_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedcampRegistration',
            new_name='CampRegistration',
        ),
    ]
