# Generated by Django 2.1.5 on 2019-04-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0005_auto_20190423_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='campregistration',
            name='file',
            field=models.FileField(default=1, upload_to='campfiles/'),
            preserve_default=False,
        ),
    ]
