# Generated by Django 2.1.5 on 2019-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0006_campregistration_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campregistration',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='campfiles/'),
        ),
    ]
