# Generated by Django 2.1.5 on 2019-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0007_auto_20190428_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campregistration',
            name='file',
            field=models.FileField(blank=True, default=1, upload_to='campfiles/'),
            preserve_default=False,
        ),
    ]
