# Generated by Django 2.1.5 on 2019-05-13 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190513_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainregister',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Type'),
        ),
    ]
