# Generated by Django 2.1.5 on 2019-04-04 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_servantrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servantrequest',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.JobType'),
        ),
    ]
