# Generated by Django 2.1.5 on 2019-04-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_regservant_job_type'),
        ('user', '0004_auto_20190404_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='servantrequest',
            name='servant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.RegServant'),
            preserve_default=False,
        ),
    ]
