# Generated by Django 2.1.5 on 2019-04-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_servantrequest_servant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='image',
            field=models.ImageField(blank=True, default='bookicon.png', null=True, upload_to='bookfiles/'),
        ),
    ]
