# Generated by Django 2.1.5 on 2019-04-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190410_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memreg',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profilepics/'),
        ),
    ]
