# Generated by Django 2.1.5 on 2019-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190410_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memreg',
            name='photo',
            field=models.ImageField(blank=True, default='profilepics/default.jpg', null=True, upload_to='profilepics/'),
        ),
    ]
