# Generated by Django 2.1.5 on 2019-04-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190411_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='image',
            field=models.ImageField(blank=True, default='bookfiles/bookicon.png', upload_to='bookfiles/'),
        ),
    ]
