# Generated by Django 2.1.5 on 2019-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190411_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memreg',
            name='photo',
            field=models.ImageField(blank=True, default='profilepics/default.jpg', upload_to='profilepics/'),
        ),
    ]
